import { Header } from '@/components/shared';
import React from 'react';

export const metadata = {
  title: 'CheckoutLayout',
  description: 'Generated by Next.js',
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header hasSearch={false} hasCart={false} className='bg-[#F4F1EE]' />
      <main className='min-h-screen bg-[#F4F1EE]'>{children}</main>
    </>
  );
}
